# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 16:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcardpaymentmethod',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_payments.creditcardpaymentmethod_set+', to='contenttypes.ContentType'),
        ),
    ]
