# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0003_auto_20170824_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseplate',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
